### ISSUE TITLE
Partial mapping

### ISSUE THREAD

**Issue by neroux** [oblac/jodd-json#1]
@igr, I guess right now it is not possible to parse/map a JSON document only partially, right?

By that I mean only e.g. "field1" in this document

```json
{
	"field1": [
		{
			"something": "else",
			"somemore": "yesplease"
		}
	],

	"field2": true,
	"field3": 1
}
```

I tried something of that sort but didn't get very far

```java
new JsonParser()
	.map("field1.values", MyMappingClass.class)
	.parse(JSON-HERE);
```

Thanks :)

**Comment by igr** [comment]
Ah this should work! It seems arrays are not handled well...
Fixing!

**Comment by neroux** [comment]
So my assumption was not completely off? :)

It is probably not possible, however, to have `parse` just return the mapped values from "field1", right?

**Comment by igr** [comment]
OK, let me answer you, it seems everything works.

## partial parsing

First, Jodd can't partially parse a JSON, meaning, just to parse a field (and everything below), skipping the rest of the JSON. Jodd must parse the whole JSON.

The closes thing to partial parsing is _lazy_ parsing. When enabled, JSON is parsed only as you need. In your example, only the first level would be parsed, until you ask for the `field1` - then Jodd will kick in and parse more.

(not sure if this is what you want0

## mapping

Mapping is just how some part of JSON is going to parsed (the whole JSON is parsed still). The following variants works:

### 1 

```java
final Map<String, Object> m = new JsonParser()
				.map("values.values", MyMappingClass.class)
				.parse(json);

final List<MyMappingClass> mm = (List<MyMappingClass>) m.get("field1");
```

In the default mode, you can't specify a direct path, only rules for ALL elements on the path. Hence, you can't use `field1.values` here.

### 2 - alt mode

If you want to use the path as you specified, you need to enable the `altPaths`. They have some performance penalties:

```java
final Map<String, Object> m = new JsonParser()
		.map("field1.values", MyMappingClass.class)
		.useAltPaths()
		.parse(json);

final List<MyMappingClass> mm = (List<MyMappingClass>) m.get("field1");
```

This way only `field1.values` is going to be mapped to `MyMappingClass`.

---

Now thinking out loud, it would be cool to enable altPaths without the performance penalty...
will add this as a potential improvement!

**Comment by igr** [comment]
Closing this one, let me know if you need anything more!

**Comment by neroux** [comment]
> First, Jodd can't partially parse a JSON

I thought so :). Would just have been nice, particularly in cases where one is looking only for a particular child element.

> Mapping is just how some part of JSON is going to parsed (the whole JSON is parsed still).

So, it actually was not a bug but I'd need to use `altPaths`? Let me try please

**Comment by igr** [comment]
I tried for you :)

https://github.com/oblac/jodd-json/blob/master/src/test/java/jodd/json/PartialTest.java

**Comment by neroux** [comment]
Thanks, I just tried it and it does seem to have worked :)

Apologies for missing `altPaths`.

**Comment by igr** [comment]
Need to write a better documentation :))))

**Comment by neroux** [comment]
Or I need to pay closer attention to it :-D

Seriously, of course there are bits that can be improved but overall the documentation is pretty good. Much better than what IBM provides for their Java integration for Notes.

**Comment by igr** [comment]
Hahaaa, IBM! :)))))) True that :))))
