### ISSUE TITLE
JsonParser seemingly not thread-safe

### ISSUE THREAD

**Issue by neroux** [oblac/jodd-json#4]
When using a common `JsonParser` instance I occasionally get string parsing exceptions.

From what I can tell that would be a multi-threading issue and JsonParser would not be thread-safe in that case. That's not necessarily a bug, but something to be aware of :)

**Comment by igr** [comment]
Yeah, you should create a new instance every time... It's meant to be short-lived, hence collected by GC soon. I didn't take any particular thread-safety measures. I guess I could add this to the documentation :)

**Comment by neroux** [comment]
Thanks for the confirmation. I wanted to use a common instance to avoid having to instantiate it over and over again.
